config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  default_url_options host: 'localhost:3000/'

  devise_for :users, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    registration: 'signup'
  }, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :daily_records
  get 'profile', to: 'users#profile'
  post 'social_auth/callback', to: 'users/social_auth#authenticate_social_auth_user'
end

app/models/application_record.rb
# frozen_string_literal: true

# app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/daily_record.rb
# frozen_string_literal: true

# app/models/daily_record.rb
class DailyRecord < ApplicationRecord
  include Rails.application.routes.url_helpers

  has_one_attached :image
  belongs_to :user

  def image_url
    image.attached? ? url_for(image) : ''
  end

  def self.filter(opts)
    result = if opts[:id]
               DailyRecord.find(opts[:id])
             else
               res = DailyRecord.page(opts[:page]).per(10).all
               res.where(opts[:query]) if opts[:query].present?
               res
             end
    DailyRecordSerializer.new(result)
  end
end

app/models/jwt_blacklist.rb
# frozen_string_literal: true

# app/models/jwt_blacklist.rb
class JwtBlacklist < ApplicationRecord
  include Devise::JWT::RevocationStrategies::Denylist
  self.table_name = 'jwt_blacklists'
end

app/models/user.rb
# frozen_string_literal: true

# app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :jwt_authenticatable, jwt_revocation_strategy: JwtBlacklist

  devise :omniauthable, omniauth_providers: [:facebook]

  has_many :daily_records, dependent: :destroy

  def self.signin_or_create_from_provider(provider_data)
    where(provider: provider_data[:provider], uid: provider_data[:uid]).first_or_create do |user|
      user.email = provider_data[:info][:email]
      user.password = Devise.friendly_token[0, 20]
    end
  end

  def create_new_auth_token
    JWT.encode({ user_id: id, exp: 24.hours.from_now.to_i }, Rails.application.secrets.secret_key_base.to_s)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :check_request_agent_type

  private

  def check_request_agent_type
    return true if request.user_agent =~ /android|blackberry|iphone|ipod|iemobile|mobile|webos/

    render json: { message: 'Please send request Via mobile devise' }
  end
end

app/controllers/daily_records_controller.rb
# frozen_string_literal: true

# app/controllers/daily_records_controller.rb
class DailyRecordsController < ApplicationController
  before_action :set_daily_record, only: %i[edit update destroy]
  skip_before_action :verify_authenticity_token
  before_action :authenticate_user!

  def index
    @daily_records = DailyRecord.filter(params)
    render json: { daily_records: @daily_records.serializable_hash }, status: 200
  end

  def show
    @daily_record = DailyRecord.filter(params)
    render json: { daily_records: @daily_record.serializable_hash }, status: 200
  end

  def new
    @daily_record = DailyRecord.new
  end

  def edit; end

  def create
    @daily_record = DailyRecord.new(daily_record_params)

    respond_to do |format|
      if @daily_record.save
        format.json { render :show, format: :json }
      else
        format.json { render json: @daily_record.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @daily_record.update(daily_record_params)
        format.json { render :show, format: :json }
      else
        format.json { render json: @daily_record.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @daily_record = DailyRecord.filter(params).destroy_record
    render json: { message: 'Daily record was successfully destroyed.', data: @daily_record }
  end

  private

  def set_daily_record
    @daily_record = DailyRecord.find(params[:id])
  end

  def daily_record_params
    params.require(:daily_record).permit(:note, :date, :user_id, :image)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

module Users
  # app/controllers/users/registrations_controller.rb
  class RegistrationsController < Devise::RegistrationsController
    skip_before_action :verify_authenticity_token

    respond_to :json

    private

    def respond_with(resource, _opts = {})
      render json: {
        status: { code: 200, message: 'Logged in successfully.' },
        data: UserSerializer.new(resource).serializable_hash[:data][:attributes]
      }
    end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

module Users
  # app/controllers/users/registrations_controller.rb
  class SessionsController < Devise::SessionsController
    skip_before_action :verify_authenticity_token

    respond_to :json

    private

    def respond_with(resource, _opts = {})
      render json: {
        status: { code: 200, message: 'Logged in successfully.' },
        data: UserSerializer.new(resource).serializable_hash[:data][:attributes]
      }
    end

    def respond_to_on_destroy
      head :ok
    end
  end
end

app/controllers/users/social_auth_controller.rb
# frozen_string_literal: true

module Users
  # app/controllers/users/social_auth_controller.rb
  class SocialAuthController < ApplicationController
    skip_before_action :verify_authenticity_token

    def authenticate_social_auth_user
      @user = User.signin_or_create_from_provider(params)
      if @user.persisted?
        sign_in(@user)

        response.headers['Authorization'] = "Bearer #{@user.create_new_auth_token}"
        message = 'User was successfully logged in through Facebook'
        construct_response(:created, message, UserSerializer.new(@user).serializable_hash)
      else
        message = 'There was a problem signing you in through Facebook'
        construct_response(:unprocessable_entity, message, data: @user.errors.full_messages)
      end
    end

    private

    def construct_response(status, message, payload)
      render json: {
        message: message
      }.merge(payload), status: status
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# app/controllers/users_controller.rb
class UsersController < ApplicationController
  def profile
    query = { query: { user: current_user.id } }
    daily_records = DailyRecord.filter(query) if current_user.daily_records
    render json: { daily_records: daily_records }, status: 200
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/daily_records_helper.rb
# frozen_string_literal: true

# app/helpers/daily_records_helper.rb
module DailyRecordsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

# app/helpers/users_helper.rb
module UsersHelper
end

app/views/daily_records/_form.html.erb
<%= form_with(model: daily_record) do |form| %>
  <% if daily_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(daily_record.errors.count, "error") %> prohibited this daily_record from being saved:</h2>

      <ul>
        <% daily_record.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="field">
    <%= form.label :note %>
    <%= form.text_field :note %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/daily_records/edit.html.erb
<h1>Editing Daily Record</h1>

<%= render 'form', daily_record: @daily_record %>

<%= link_to 'Show', @daily_record %> |
<%= link_to 'Back', daily_records_path %>

app/views/daily_records/index.html.erb
<%= paginate @daily_records %>

<p id="notice"><%= notice %></p>

<h1>Daily Records</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Note</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @daily_records.each do |daily_record| %>
      <tr>
        <td><%= daily_record.image %></td>
        <td><%= daily_record.note %></td>
        <td><%= daily_record.date %></td>
        <td><%= link_to 'Show', daily_record %></td>
        <td><%= link_to 'Edit', edit_daily_record_path(daily_record) %></td>
        <td><%= link_to 'Destroy', daily_record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Daily Record', new_daily_record_path %>

app/views/daily_records/new.html.erb
<h1>New Daily Record</h1>

<%= render 'form', daily_record: @daily_record %>

<%= link_to 'Back', daily_records_path %>

app/views/daily_records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= @daily_record.image %>
</p>

<p>
  <strong>Note:</strong>
  <%= @daily_record.note %>
</p>

<p>
  <strong>Date:</strong>
  <%= @daily_record.date %>
</p>

<%= link_to 'Edit', edit_daily_record_path(@daily_record) %> |
<%= link_to 'Back', daily_records_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/user.html.erb
<% @users.each do |user| %>
  <%=user.image %>
  <%= user.note %>
  <%= user.date %>
<% end %>